---
    environment: production
    user: www-data
    group: www-data
    pid: tmp/thin.pid
    log: log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
