---
    environment: production
    chdir: /var/www/rbtorrent
    address: 127.0.0.1
    user: www-data
    group: www-data
    port: 4567
    pid: /var/www/rbtorrent/thin.pid
    rackup: /var/www/rbtorrent/config.ru
    log: /var/www/rbtorrent/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
